//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edge.Drivers.WeMo.WeMoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="WeMoServiceReference.BasicServicePortType")]
    public interface BasicServicePortType {
        
        // CODEGEN: Generating message contract since the operation SetBinaryState is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#SetBinaryState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse1 SetBinaryState(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#SetBinaryState", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse1> SetBinaryStateAsync(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest request);
        
        // CODEGEN: Generating message contract since the operation GetBinaryState is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetBinaryState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse1 GetBinaryState(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetBinaryState", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse1> GetBinaryStateAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest request);
        
        // CODEGEN: Generating message contract since the operation GetFriendlyName is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetFriendlyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse1 GetFriendlyName(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetFriendlyName", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse1> GetFriendlyNameAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest request);
        
        // CODEGEN: Generating message contract since the operation GetHomeId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetHomeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse1 GetHomeId(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetHomeId", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse1> GetHomeIdAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest request);
        
        // CODEGEN: Generating message contract since the operation GetSignalStrength is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetSignalStrength", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse1 GetSignalStrength(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetSignalStrength", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse1> GetSignalStrengthAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest request);
        
        // CODEGEN: Generating message contract since the operation GetLogFileURL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetLogFileURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse1 GetLogFileURL(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetLogFileURL", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse1> GetLogFileURLAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest request);
        
        // CODEGEN: Generating message contract since the operation GetIconURL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetIconURL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse1 GetIconURL(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#GetIconURL", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse1> GetIconURLAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest request);
        
        // CODEGEN: Generating message contract since the operation ChangeFriendlyName is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#ChangeFriendlyName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse1 ChangeFriendlyName(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Belkin:service:basicevent:1#ChangeFriendlyName", ReplyAction="*")]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse1> ChangeFriendlyNameAsync(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class SetBinaryState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class SetBinaryStateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBinaryStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryState SetBinaryState;
        
        public SetBinaryStateRequest() {
        }
        
        public SetBinaryStateRequest(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryState SetBinaryState) {
            this.SetBinaryState = SetBinaryState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBinaryStateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse SetBinaryStateResponse;
        
        public SetBinaryStateResponse1() {
        }
        
        public SetBinaryStateResponse1(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse SetBinaryStateResponse) {
            this.SetBinaryStateResponse = SetBinaryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetBinaryState : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetBinaryStateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string binaryStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BinaryState {
            get {
                return this.binaryStateField;
            }
            set {
                this.binaryStateField = value;
                this.RaisePropertyChanged("BinaryState");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBinaryStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryState GetBinaryState;
        
        public GetBinaryStateRequest() {
        }
        
        public GetBinaryStateRequest(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryState GetBinaryState) {
            this.GetBinaryState = GetBinaryState;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBinaryStateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse GetBinaryStateResponse;
        
        public GetBinaryStateResponse1() {
        }
        
        public GetBinaryStateResponse1(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse GetBinaryStateResponse) {
            this.GetBinaryStateResponse = GetBinaryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetFriendlyName : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetFriendlyNameResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendlyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyName GetFriendlyName;
        
        public GetFriendlyNameRequest() {
        }
        
        public GetFriendlyNameRequest(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyName GetFriendlyName) {
            this.GetFriendlyName = GetFriendlyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFriendlyNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse GetFriendlyNameResponse;
        
        public GetFriendlyNameResponse1() {
        }
        
        public GetFriendlyNameResponse1(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse GetFriendlyNameResponse) {
            this.GetFriendlyNameResponse = GetFriendlyNameResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetHomeId : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetHomeIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string homeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HomeId {
            get {
                return this.homeIdField;
            }
            set {
                this.homeIdField = value;
                this.RaisePropertyChanged("HomeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHomeIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetHomeId GetHomeId;
        
        public GetHomeIdRequest() {
        }
        
        public GetHomeIdRequest(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeId GetHomeId) {
            this.GetHomeId = GetHomeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHomeIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse GetHomeIdResponse;
        
        public GetHomeIdResponse1() {
        }
        
        public GetHomeIdResponse1(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse GetHomeIdResponse) {
            this.GetHomeIdResponse = GetHomeIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetSignalStrength : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetSignalStrengthResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string signalStrengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignalStrength {
            get {
                return this.signalStrengthField;
            }
            set {
                this.signalStrengthField = value;
                this.RaisePropertyChanged("SignalStrength");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignalStrengthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrength GetSignalStrength;
        
        public GetSignalStrengthRequest() {
        }
        
        public GetSignalStrengthRequest(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrength GetSignalStrength) {
            this.GetSignalStrength = GetSignalStrength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSignalStrengthResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse GetSignalStrengthResponse;
        
        public GetSignalStrengthResponse1() {
        }
        
        public GetSignalStrengthResponse1(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse GetSignalStrengthResponse) {
            this.GetSignalStrengthResponse = GetSignalStrengthResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetLogFileURL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetLogFileURLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lOGURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGURL {
            get {
                return this.lOGURLField;
            }
            set {
                this.lOGURLField = value;
                this.RaisePropertyChanged("LOGURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogFileURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURL GetLogFileURL;
        
        public GetLogFileURLRequest() {
        }
        
        public GetLogFileURLRequest(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURL GetLogFileURL) {
            this.GetLogFileURL = GetLogFileURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogFileURLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse GetLogFileURLResponse;
        
        public GetLogFileURLResponse1() {
        }
        
        public GetLogFileURLResponse1(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse GetLogFileURLResponse) {
            this.GetLogFileURLResponse = GetLogFileURLResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetIconURL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class GetIconURLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIconURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetIconURL GetIconURL;
        
        public GetIconURLRequest() {
        }
        
        public GetIconURLRequest(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURL GetIconURL) {
            this.GetIconURL = GetIconURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIconURLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse GetIconURLResponse;
        
        public GetIconURLResponse1() {
        }
        
        public GetIconURLResponse1(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse GetIconURLResponse) {
            this.GetIconURLResponse = GetIconURLResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class ChangeFriendlyName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string friendlyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FriendlyName {
            get {
                return this.friendlyNameField;
            }
            set {
                this.friendlyNameField = value;
                this.RaisePropertyChanged("FriendlyName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:Belkin:service:basicevent:1")]
    public partial class ChangeFriendlyNameResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeFriendlyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyName ChangeFriendlyName;
        
        public ChangeFriendlyNameRequest() {
        }
        
        public ChangeFriendlyNameRequest(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyName ChangeFriendlyName) {
            this.ChangeFriendlyName = ChangeFriendlyName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeFriendlyNameResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Belkin:service:basicevent:1", Order=0)]
        public Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse ChangeFriendlyNameResponse;
        
        public ChangeFriendlyNameResponse1() {
        }
        
        public ChangeFriendlyNameResponse1(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse ChangeFriendlyNameResponse) {
            this.ChangeFriendlyNameResponse = ChangeFriendlyNameResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BasicServicePortTypeChannel : Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicServicePortTypeClient : System.ServiceModel.ClientBase<Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType>, Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType {
        
        public BasicServicePortTypeClient() {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.SetBinaryState(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest request) {
            return base.Channel.SetBinaryState(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse SetBinaryState(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryState SetBinaryState1) {
            Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest();
            inValue.SetBinaryState = SetBinaryState1;
            Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).SetBinaryState(inValue);
            return retVal.SetBinaryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.SetBinaryStateAsync(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest request) {
            return base.Channel.SetBinaryStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateResponse1> SetBinaryStateAsync(Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryState SetBinaryState) {
            Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.SetBinaryStateRequest();
            inValue.SetBinaryState = SetBinaryState;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).SetBinaryStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetBinaryState(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest request) {
            return base.Channel.GetBinaryState(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse GetBinaryState(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryState GetBinaryState1) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest();
            inValue.GetBinaryState = GetBinaryState1;
            Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetBinaryState(inValue);
            return retVal.GetBinaryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetBinaryStateAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest request) {
            return base.Channel.GetBinaryStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateResponse1> GetBinaryStateAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryState GetBinaryState) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetBinaryStateRequest();
            inValue.GetBinaryState = GetBinaryState;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetBinaryStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetFriendlyName(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest request) {
            return base.Channel.GetFriendlyName(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse GetFriendlyName(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyName GetFriendlyName1) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest();
            inValue.GetFriendlyName = GetFriendlyName1;
            Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetFriendlyName(inValue);
            return retVal.GetFriendlyNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetFriendlyNameAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest request) {
            return base.Channel.GetFriendlyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameResponse1> GetFriendlyNameAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyName GetFriendlyName) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetFriendlyNameRequest();
            inValue.GetFriendlyName = GetFriendlyName;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetFriendlyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetHomeId(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest request) {
            return base.Channel.GetHomeId(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse GetHomeId(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeId GetHomeId1) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest();
            inValue.GetHomeId = GetHomeId1;
            Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetHomeId(inValue);
            return retVal.GetHomeIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetHomeIdAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest request) {
            return base.Channel.GetHomeIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdResponse1> GetHomeIdAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetHomeId GetHomeId) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetHomeIdRequest();
            inValue.GetHomeId = GetHomeId;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetHomeIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetSignalStrength(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest request) {
            return base.Channel.GetSignalStrength(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse GetSignalStrength(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrength GetSignalStrength1) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest();
            inValue.GetSignalStrength = GetSignalStrength1;
            Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetSignalStrength(inValue);
            return retVal.GetSignalStrengthResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetSignalStrengthAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest request) {
            return base.Channel.GetSignalStrengthAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthResponse1> GetSignalStrengthAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrength GetSignalStrength) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetSignalStrengthRequest();
            inValue.GetSignalStrength = GetSignalStrength;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetSignalStrengthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetLogFileURL(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest request) {
            return base.Channel.GetLogFileURL(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse GetLogFileURL(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURL GetLogFileURL1) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest();
            inValue.GetLogFileURL = GetLogFileURL1;
            Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetLogFileURL(inValue);
            return retVal.GetLogFileURLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetLogFileURLAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest request) {
            return base.Channel.GetLogFileURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLResponse1> GetLogFileURLAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURL GetLogFileURL) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetLogFileURLRequest();
            inValue.GetLogFileURL = GetLogFileURL;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetLogFileURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetIconURL(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest request) {
            return base.Channel.GetIconURL(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse GetIconURL(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURL GetIconURL1) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest();
            inValue.GetIconURL = GetIconURL1;
            Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetIconURL(inValue);
            return retVal.GetIconURLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.GetIconURLAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest request) {
            return base.Channel.GetIconURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLResponse1> GetIconURLAsync(Edge.Drivers.WeMo.WeMoServiceReference.GetIconURL GetIconURL) {
            Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.GetIconURLRequest();
            inValue.GetIconURL = GetIconURL;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).GetIconURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse1 Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.ChangeFriendlyName(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest request) {
            return base.Channel.ChangeFriendlyName(request);
        }
        
        public Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse ChangeFriendlyName(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyName ChangeFriendlyName1) {
            Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest();
            inValue.ChangeFriendlyName = ChangeFriendlyName1;
            Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse1 retVal = ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).ChangeFriendlyName(inValue);
            return retVal.ChangeFriendlyNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse1> Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType.ChangeFriendlyNameAsync(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest request) {
            return base.Channel.ChangeFriendlyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameResponse1> ChangeFriendlyNameAsync(Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyName ChangeFriendlyName) {
            Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest inValue = new Edge.Drivers.WeMo.WeMoServiceReference.ChangeFriendlyNameRequest();
            inValue.ChangeFriendlyName = ChangeFriendlyName;
            return ((Edge.Drivers.WeMo.WeMoServiceReference.BasicServicePortType)(this)).ChangeFriendlyNameAsync(inValue);
        }
    }
}
